#!/usr/bin/env python3
"""Regenerate the golden fixtures for the Go catalog writer (specs/002, I3).

Runs the ACTUAL Python pipeline writer (src/mmeq/export/writer.py) on the
synthetic inputs in this directory, so the Go tests assert byte-equality
against real pandas/json.dump output rather than a hand-maintained snapshot.

Usage (from the repo root):

    .venv/bin/python go/internal/catalog/testdata/gen_golden.py

Inputs (checked in, hand-written):
    input_existing.json   records already in the "combined" store
    input_new.json        records of a new fetch (includes Myanmar UTF-8 names,
                          null/missing numerics, 90.0 / 3.6 / 24.441 floats,
                          duplicate ids for keep-last dedup, commas + quotes
                          in string fields)

Outputs (checked in, regenerated by this script):
    existing_combined.csv / existing_combined.json
        the pre-existing store both writers merge against (Python-written, so
        the read -> rewrite round trip is an identity)
    golden_monthly.csv / golden_monthly.json
        save_to_csv(new, overwrite=True) / save_to_json(new)
    golden_merged.csv / golden_merged.json
        save_to_csv(new, dedup=True) on top of existing_combined.csv /
        merge_combined_json(existing, new)
    golden_merged_fresh.csv / golden_merged_fresh.json
        the same merge operations with NO existing file

Value coercion: JSON integers are coerced to float before building the
DataFrame, mirroring Go's encoding/json which decodes every JSON number to
float64 — this is the contract the Go writer is tested against.

Column order: DEFAULT_COLUMNS (the production CSV header) restricted to the
keys present, then unknown keys in sorted order — the same rule as
catalog.ColumnsFor in the Go package (pandas normally inherits the API dict
order, which Go maps cannot preserve).
"""

import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
sys.path.insert(0, os.path.join(REPO, "src"))

import pandas as pd  # noqa: E402

from mmeq.export.writer import (  # noqa: E402
    load_combined_json,
    merge_combined_json,
    save_to_csv,
    save_to_json,
)

# Must match catalog.DefaultColumns in ../writer.go (the production header of
# quake_exports/csv/monthly/*.csv).
DEFAULT_COLUMNS = [
    "latitude", "longitude", "depth", "mag", "magType", "nst", "gap", "dmin",
    "rms", "net", "id", "updated", "location", "place", "country", "continent",
    "type", "timeAdded", "timestamp", "locationInferred", "state",
    "initialPosition", "shakemapURL", "shakemapLastUpdated", "time_utc",
    "time_mmt", "state_region", "district", "township", "nearest_city",
    "place_type", "distance_km",
]


def load_records(name):
    with open(os.path.join(HERE, name), encoding="utf-8") as f:
        records = json.load(f)
    # Mirror Go's encoding/json: every JSON number decodes to float64.
    return [
        {
            k: float(v) if isinstance(v, int) and not isinstance(v, bool) else v
            for k, v in rec.items()
        }
        for rec in records
    ]


def order_columns(present):
    """catalog.ColumnsFor: DEFAULT_COLUMNS ∩ present, then sorted leftovers."""
    known = [c for c in DEFAULT_COLUMNS if c in present]
    return known + sorted(set(present) - set(DEFAULT_COLUMNS))


def frame(records):
    df = pd.DataFrame(records)
    return df[order_columns(set(df.columns))]


def dump_json(payload, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)


def main():
    existing_df = frame(load_records("input_existing.json"))
    new_df = frame(load_records("input_new.json"))

    p = lambda name: os.path.join(HERE, name)  # noqa: E731

    # --- inputs for the Go merge tests (must themselves be Python-written) ---
    save_to_csv(existing_df, p("existing_combined.csv"), overwrite=True)
    save_to_json(existing_df, p("existing_combined.json"))

    # --- monthly semantics: overwrite with just the new frame, no dedup ------
    save_to_csv(new_df, p("golden_monthly.csv"), overwrite=True)
    save_to_json(new_df, p("golden_monthly.json"))

    # --- yearly/combined CSV: merge with existing file, dedup on id ----------
    shutil.copyfile(p("existing_combined.csv"), p("golden_merged.csv"))
    save_to_csv(new_df, p("golden_merged.csv"), dedup=True)

    if os.path.exists(p("golden_merged_fresh.csv")):
        os.remove(p("golden_merged_fresh.csv"))
    save_to_csv(new_df, p("golden_merged_fresh.csv"), dedup=True)

    # --- combined JSON merge: id-keyed, first-seen order, later wins ---------
    existing_records = load_combined_json(p("existing_combined.json"))
    new_records = new_df.to_dict(orient="records")
    dump_json(
        {"earthquakes": merge_combined_json(existing_records, new_records)},
        p("golden_merged.json"),
    )
    dump_json(
        {"earthquakes": merge_combined_json([], new_records)},
        p("golden_merged_fresh.json"),
    )

    print("golden fixtures regenerated under", HERE)


if __name__ == "__main__":
    main()
